spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30000
      max-request-size: 30000


mybatis:
  type-aliases-package: com.liu.studentmanager.domain
  mapper-locations: classpath:mapper/**.xml

